import streamlit as st

st.title("Description of Different Streamlit Application")


st.header('Simple Sentiment Analyzer App')
st.image("./pic/analyze.png")

with st.expander("🔮Sentiment Analyzer"):
    st.markdown("""
    
    #
                A Sentiment Analyzer

A sentiment analyzer is a powerful tool in natural language processing that evaluates text to determine its underlying sentiment or emotional tone.
                 Using algorithms and machine learning models, it classifies sentences or larger bodies of text as positive, negative, or neutral. 
                The analyzer examines various linguistic features, such as word choice, context, and syntax, to identify the feelings and attitudes 
                conveyed by the text. For example, if you input a sentence like "I love this new smartphone!", the sentiment analyzer would detect a 
                positive sentiment due to the use of the word "love" and the overall enthusiastic tone. Conversely, a sentence like "I am really disappointed
                 with this service" would be classified as negative, reflecting dissatisfaction. This tool is widely used in customer feedback analysis, social
                 media monitoring, and other applications where understanding emotional responses is crucial.
                
    """, unsafe_allow_html=True)

st.header('Image Classification')
st.image("./pic/class1.png")

with st.expander("Flower Image Classification Project"):
    st.markdown("""
    
    #
                Image Classification

In my image classification project, the focus is on accurately identifying different types of flowers from uploaded images. The project aims to classify images
                 into five distinct categories: rose, sunflower, lily, lavender, and daisy. This endeavor involves leveraging machine learning techniques, particularly
                 convolutional neural networks (CNNs), to analyze and categorize the floral images based on their distinct features.

                
    """, unsafe_allow_html=True)

st.header('🔍Prediction')
st.image("./pic/pre1.png")
st.image("./pic/pre2.png")

with st.expander("Predictions"):
    st.markdown("""
    
    #
              Prediction in Kaggle Descriptions

In Kaggle competitions, predictions refer to the outcomes generated by machine learning models on test data provided by the competition organizers. 
                Participants train their models on a labeled training dataset to learn patterns and relationships within the data. They then apply these
                 trained models to make predictions on the test dataset, which lacks labels. These predictions are submitted to Kaggle for evaluation, where
                 they are compared against the true labels to determine the model's performance. The accuracy of these predictions determines the participant's
                 ranking on the competition leaderboard.
                
    """, unsafe_allow_html=True)